# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlistcount',
            name='tier',
        ),
        migrations.DeleteModel(
            name='WaitlistCount',
        ),
    ]
