# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-23 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color_hex',
            new_name='hex',
        ),
    ]
