# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metro_manila', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('province', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maintenance_mode', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
