# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity_management', '0004_producttier_total_waitlist_count'),
        ('customer_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('U', 'Unpaid'), ('V', 'Verifying Payment'), ('P', 'Processing'), ('S', 'Shipped'), ('C', 'Cancelled')], default='U', max_length=2)),
                ('deposit_photo', models.CharField(default=None, max_length=256, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity_management.ProductTier')),
            ],
        ),
    ]
