# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170831_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='administrator_nodes',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
