# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-20 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='http://i.imgur.com/a0HmrDW.png', max_length=256),
        ),
    ]
