# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity_management', '0002_auto_20170820_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('image', models.CharField(default='http://i.imgur.com/a0HmrDW.png', max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity_management.Stall')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity_management.ProductDescription')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='stall',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='product_tier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entity_management.ProductTier'),
            preserve_default=False,
        ),
    ]
