# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-20 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity_management', '0004_producttier_total_waitlist_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttier',
            name='total_waitlist_count',
        ),
    ]
