# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity_management', '0005_remove_producttier_total_waitlist_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stall',
            new_name='Collection',
        ),
        migrations.RenameField(
            model_name='productdescription',
            old_name='stall',
            new_name='collection',
        ),
    ]
