# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity_management', '0004_producttier_total_waitlist_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity_management.ProductDescription')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPairOccurrences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_1', to='entity_management.ProductDescription')),
                ('product_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_2', to='entity_management.ProductDescription')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lift', models.FloatField(default=0)),
                ('associated_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_product', to='entity_management.ProductDescription')),
                ('root_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_product', to='entity_management.ProductDescription')),
            ],
        ),
    ]
