# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_auto_20170902_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='confidence',
            field=models.FloatField(default=0),
        ),
    ]
